// Code generated by protoc-gen-go. DO NOT EDIT.
// source: syncer.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	syncer.proto

It has these top-level messages:
	LockRequest
	Reply
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LockRequest struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Locktimeout string `protobuf:"bytes,2,opt,name=locktimeout" json:"locktimeout,omitempty"`
}

func (m *LockRequest) Reset()                    { *m = LockRequest{} }
func (m *LockRequest) String() string            { return proto.CompactTextString(m) }
func (*LockRequest) ProtoMessage()               {}
func (*LockRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LockRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LockRequest) GetLocktimeout() string {
	if m != nil {
		return m.Locktimeout
	}
	return ""
}

type Reply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Reply) Reset()                    { *m = Reply{} }
func (m *Reply) String() string            { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()               {}
func (*Reply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Reply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*LockRequest)(nil), "pb.LockRequest")
	proto.RegisterType((*Reply)(nil), "pb.Reply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Syncer service

type SyncerClient interface {
	Lock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*Reply, error)
	Unlock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*Reply, error)
}

type syncerClient struct {
	cc *grpc.ClientConn
}

func NewSyncerClient(cc *grpc.ClientConn) SyncerClient {
	return &syncerClient{cc}
}

func (c *syncerClient) Lock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/pb.Syncer/Lock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncerClient) Unlock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/pb.Syncer/Unlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Syncer service

type SyncerServer interface {
	Lock(context.Context, *LockRequest) (*Reply, error)
	Unlock(context.Context, *LockRequest) (*Reply, error)
}

func RegisterSyncerServer(s *grpc.Server, srv SyncerServer) {
	s.RegisterService(&_Syncer_serviceDesc, srv)
}

func _Syncer_Lock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncerServer).Lock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Syncer/Lock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncerServer).Lock(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Syncer_Unlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncerServer).Unlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Syncer/Unlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncerServer).Unlock(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Syncer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Syncer",
	HandlerType: (*SyncerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lock",
			Handler:    _Syncer_Lock_Handler,
		},
		{
			MethodName: "Unlock",
			Handler:    _Syncer_Unlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "syncer.proto",
}

func init() { proto.RegisterFile("syncer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xae, 0xcc, 0x4b,
	0x4e, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xb2, 0xe7, 0xe2,
	0xf6, 0xc9, 0x4f, 0xce, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xe2, 0xe3, 0x62, 0xca,
	0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x11, 0x52, 0xe0, 0xe2, 0xce,
	0xc9, 0x4f, 0xce, 0x2e, 0xc9, 0xcc, 0x4d, 0xcd, 0x2f, 0x2d, 0x91, 0x60, 0x02, 0x4b, 0x20, 0x0b,
	0x29, 0x29, 0x72, 0xb1, 0x06, 0xa5, 0x16, 0xe4, 0x54, 0x0a, 0x49, 0x70, 0xb1, 0xe7, 0xa6, 0x16,
	0x17, 0x27, 0xa6, 0xa7, 0x42, 0xf5, 0xc3, 0xb8, 0x46, 0x61, 0x5c, 0x6c, 0xc1, 0x60, 0x7b, 0x85,
	0x54, 0xb8, 0x58, 0x40, 0xb6, 0x09, 0xf1, 0xeb, 0x15, 0x24, 0xe9, 0x21, 0xd9, 0x2b, 0xc5, 0x09,
	0x12, 0x00, 0x9b, 0xa3, 0xc4, 0x20, 0xa4, 0xc6, 0xc5, 0x16, 0x9a, 0x97, 0x43, 0x50, 0x5d, 0x12,
	0x1b, 0xd8, 0x1b, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x02, 0x33, 0x1f, 0x9a, 0xd6, 0x00,
	0x00, 0x00,
}
